/* TODO: spec citations per structure */
#include <drivers/nvme.h>
#include <drivers/verifier.h>

dv_layout(nvme_regs, 0x1020);
dv_field(nvme_regs, cap_lo, 0x0, 4);
dv_field(nvme_regs, cap_hi, 0x4, 4);
dv_field(nvme_regs, version, 0x8, 4);
dv_field(nvme_regs, intms, 0xc, 4);
dv_field(nvme_regs, intmc, 0x10, 4);
dv_field(nvme_regs, cc, 0x14, 4);
dv_field(nvme_regs, nssr, 0x18, 4);
dv_field(nvme_regs, csts, 0x1c, 4);
dv_field(nvme_regs, reserved1, 0x20, 4);
dv_field(nvme_regs, aqa, 0x24, 4);
dv_field(nvme_regs, asq_lo, 0x28, 4);
dv_field(nvme_regs, asq_hi, 0x2c, 4);
dv_field(nvme_regs, acq_lo, 0x30, 4);
dv_field(nvme_regs, acq_hi, 0x34, 4);
dv_field(nvme_regs, reserved4, 0x38, 4072);

dv_layout(nvme_command, 0x40);
dv_field(nvme_command, opc, 0x0, 1);
dv_field(nvme_command, fuse, 0x1, 1);
dv_field(nvme_command, cid, 0x2, 2);
dv_field(nvme_command, nsid, 0x4, 4);
dv_field(nvme_command, rsvd2, 0x8, 8);
dv_field(nvme_command, mptr, 0x10, 8);
dv_field(nvme_command, prp1, 0x18, 8);
dv_field(nvme_command, prp2, 0x20, 8);
dv_field(nvme_command, cdw10, 0x28, 4);
dv_field(nvme_command, cdw11, 0x2c, 4);
dv_field(nvme_command, cdw12, 0x30, 4);
dv_field(nvme_command, cdw13, 0x34, 4);
dv_field(nvme_command, cdw14, 0x38, 4);
dv_field(nvme_command, cdw15, 0x3c, 4);

dv_layout(nvme_completion, 0x10);
dv_field(nvme_completion, result, 0x0, 4);
dv_field(nvme_completion, rsvd, 0x4, 4);
dv_field(nvme_completion, sq_head, 0x8, 2);
dv_field(nvme_completion, sq_id, 0xa, 2);
dv_field(nvme_completion, cid, 0xc, 2);
dv_field(nvme_completion, status, 0xe, 2);

dv_layout(nvme_cc, 0x4);

dv_layout(nvme_lbaf, 0x4);
dv_field(nvme_lbaf, ms, 0x0, 2);
dv_field(nvme_lbaf, lbads, 0x2, 1);
/* bitfields, not offsetof-able: rp, reserved */

dv_layout(nvme_identify_namespace, 0x1000);
dv_field(nvme_identify_namespace, nsze, 0x0, 8);
dv_field(nvme_identify_namespace, ncap, 0x8, 8);
dv_field(nvme_identify_namespace, nuse, 0x10, 8);
dv_field(nvme_identify_namespace, nsfeat, 0x18, 1);
dv_field(nvme_identify_namespace, nlbaf, 0x19, 1);
dv_field(nvme_identify_namespace, flbas, 0x1a, 1);
dv_field(nvme_identify_namespace, mc, 0x1b, 1);
dv_field(nvme_identify_namespace, dpc, 0x1c, 1);
dv_field(nvme_identify_namespace, dps, 0x1d, 1);
dv_field(nvme_identify_namespace, nmic, 0x1e, 1);
dv_field(nvme_identify_namespace, rescap, 0x1f, 1);
dv_field(nvme_identify_namespace, fpi, 0x20, 1);
dv_field(nvme_identify_namespace, dlfeat, 0x21, 1);
dv_field(nvme_identify_namespace, nawun, 0x22, 2);
dv_field(nvme_identify_namespace, nawupf, 0x24, 2);
dv_field(nvme_identify_namespace, nacwu, 0x26, 2);
dv_field(nvme_identify_namespace, nabsn, 0x28, 2);
dv_field(nvme_identify_namespace, nabo, 0x2a, 2);
dv_field(nvme_identify_namespace, nabspf, 0x2c, 2);
dv_field(nvme_identify_namespace, noiob, 0x2e, 2);
dv_field(nvme_identify_namespace, nvmcap, 0x30, 16);
dv_field(nvme_identify_namespace, npwg, 0x40, 2);
dv_field(nvme_identify_namespace, npwa, 0x42, 2);
dv_field(nvme_identify_namespace, npdg, 0x44, 2);
dv_field(nvme_identify_namespace, npda, 0x46, 2);
dv_field(nvme_identify_namespace, nows, 0x48, 2);
dv_field(nvme_identify_namespace, mssrl, 0x4a, 2);
dv_field(nvme_identify_namespace, mcl, 0x4c, 4);
dv_field(nvme_identify_namespace, msrc, 0x50, 1);
dv_field(nvme_identify_namespace, reserved0, 0x51, 11);
dv_field(nvme_identify_namespace, adagrpid, 0x5c, 4);
dv_field(nvme_identify_namespace, reserved1, 0x60, 3);
dv_field(nvme_identify_namespace, nsattr, 0x63, 1);
dv_field(nvme_identify_namespace, nvmsetid, 0x64, 2);
dv_field(nvme_identify_namespace, endgid, 0x66, 2);
dv_field(nvme_identify_namespace, nguid, 0x68, 16);
dv_field(nvme_identify_namespace, eui64, 0x78, 8);
dv_field(nvme_identify_namespace, lbaf, 0x80, 256);
dv_field(nvme_identify_namespace, vendor_specific, 0x180, 3712);

dv_layout(nvme_identify_controller, 0x202);
dv_field(nvme_identify_controller, vid, 0x0, 2);
dv_field(nvme_identify_controller, ssvid, 0x2, 2);
dv_field(nvme_identify_controller, sn, 0x4, 20);
dv_field(nvme_identify_controller, mn, 0x18, 40);
dv_field(nvme_identify_controller, fr, 0x40, 8);
dv_field(nvme_identify_controller, rab, 0x48, 1);
dv_field(nvme_identify_controller, ieee, 0x49, 3);
dv_field(nvme_identify_controller, mic, 0x4c, 1);
dv_field(nvme_identify_controller, mdts, 0x4d, 1);
dv_field(nvme_identify_controller, cntlid, 0x4e, 2);
dv_field(nvme_identify_controller, ver, 0x50, 4);
dv_field(nvme_identify_controller, rtd3r, 0x54, 4);
dv_field(nvme_identify_controller, rtd3e, 0x58, 4);
dv_field(nvme_identify_controller, oaes, 0x5c, 4);
dv_field(nvme_identify_controller, ctratt, 0x60, 4);
dv_field(nvme_identify_controller, rsvd96, 0x64, 156);
dv_field(nvme_identify_controller, oacs, 0x100, 2);
dv_field(nvme_identify_controller, acl, 0x102, 1);
dv_field(nvme_identify_controller, aerl, 0x103, 1);
dv_field(nvme_identify_controller, frmw, 0x104, 1);
dv_field(nvme_identify_controller, lpa, 0x105, 1);
dv_field(nvme_identify_controller, elpe, 0x106, 1);
dv_field(nvme_identify_controller, npss, 0x107, 1);
dv_field(nvme_identify_controller, avscc, 0x108, 1);
dv_field(nvme_identify_controller, apsta, 0x109, 1);
dv_field(nvme_identify_controller, wctemp, 0x10a, 2);
dv_field(nvme_identify_controller, cctemp, 0x10c, 2);
dv_field(nvme_identify_controller, mtfa, 0x10e, 2);
dv_field(nvme_identify_controller, hmpre, 0x110, 4);
dv_field(nvme_identify_controller, hmmin, 0x114, 4);
dv_field(nvme_identify_controller, tnvmcap, 0x118, 16);
dv_field(nvme_identify_controller, unvmcap, 0x128, 16);
dv_field(nvme_identify_controller, rpmbs, 0x138, 4);
dv_field(nvme_identify_controller, edstt, 0x13c, 2);
dv_field(nvme_identify_controller, dsto, 0x13e, 1);
dv_field(nvme_identify_controller, fwug, 0x13f, 1);
dv_field(nvme_identify_controller, kas, 0x140, 2);
dv_field(nvme_identify_controller, hctma, 0x142, 2);
dv_field(nvme_identify_controller, mntmt, 0x144, 2);
dv_field(nvme_identify_controller, mxtmt, 0x146, 2);
dv_field(nvme_identify_controller, sanicap, 0x148, 4);
dv_field(nvme_identify_controller, rsvd228, 0x14c, 180);
dv_field(nvme_identify_controller, sqes, 0x200, 1);
dv_field(nvme_identify_controller, cqes, 0x201, 1);
