name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'kernel/**'
      - 'include/**'
  pull_request:
    paths:
      - 'kernel/**'
      - 'include/**'
  workflow_dispatch: # manual trigger
  workflow_run:
    workflows: ["Update CI Container"]
    types:
      - completed

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build (${{ matrix.compiler }} / ${{ matrix.build_type }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    container:
      image: ghcr.io/axvonx/charmos-x86-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install clang toolchain
        if: matrix.compiler == 'clang'
        run: apt-get update && apt-get install -y clang lld

      - name: Compile
        run: ./scripts/build.sh -t ${{ matrix.build_type }} --compiler ${{ matrix.compiler }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iso-${{ matrix.compiler }}-${{ matrix.build_type }}
          path: build/charmos-x86_64.iso
          retention-days: 7

  randconfig:
    name: Randconfig build (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    container:
      image: ghcr.io/axvonx/charmos-x86-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install clang toolchain
        if: matrix.compiler == 'clang'
        run: apt-get update && apt-get install -y clang lld

      - name: Compile with random compiler flags
        run: >
          ./scripts/build.sh -t RelWithDebInfo --compiler ${{ matrix.compiler }}
          --
          -DKERNEL_RANDCONFIG=ON
          -DKERNEL_RANDCONFIG_SEED=${{ github.run_id }}
